### ISSUE TITLE
Character dump link is incorrect/unable to find morgues of characters played on http://crawl.ufetubus.com

### ISSUE THREAD

**Issue by bnandaku** [jeremygurr/crawl_spicy#1]
For games played on http://crawl.ufetubus.com, I'm unable to find morgues or in-progress character dumps.  The link provided to webtiles chat is http://crawl.homedns.org/morgue/Tasonir/Tasonir.txt (for my account of Tasonir, obviously).  This link is broken and I haven't been able to find any other location with morgues.

I have a nearly won character that I'd like to be able to finish, but want to make sure I get a morgue file out of it!

**Comment by tasonir** [comment]
Ha - was accidentally logged in on a coworker's account.  This is my (tasonir)'s account :)

**Comment by jeremygurr** [comment]
Should work now.
