### ISSUE TITLE
Can't select difficulty

### ISSUE THREAD

**Issue by Soapboy** [jeremygurr/crawl_spicy#14]
Trying to play on Ufetubus server, all Spicy features are on, multiple difficulties included. But there is no difficulty screen, just your generic species/background/weapon. I'm playing through Tor, since this server doesn't work in my country, so I thought maybe this is the issues. But HellCrawl allows me to select difficulties just fine in any browser.

**Comment by jeremygurr** [comment]
Sorry just saw this. Did you figure it out? If not, paste your config in a comment and I'll check it out.
