### ISSUE TITLE
Game crashes upon killing a monster when the character has very high experience

### ISSUE THREAD

**Issue by tasonir** [jeremygurr/crawl_spicy#2]
With the no_exp_cap = true option set.

While no obvious max value is being broken, there's likely some sort of overflow/max value being broken under the hood.  I have a level 30 Kobold hunter (+1 exp aptitude) with one skill over 27 (which is not currently being trained, but other skills in the 20's are), and on killing a monster the game crashes.  The game can be resumed from the start of the floor, and after killing about the same number of monsters, it'll crash again.  If the same path is taken as before, it'll crash on the same monster.

I know local crawl clients will spit out a .crash file (or something similiarly named), hopefully you can find those to help track down the issue.  Check my player directory to see if you find something there?  Account: Tasonir.

**Comment by jeremygurr** [comment]
Thanks that was helpful. I was able to use your character to figure out the problem quickly. Should work better now.
