### ISSUE TITLE
Morgue directory doesn't exist

### ISSUE THREAD

**Issue by tasonir** [jeremygurr/crawl_spicy#3]
The morgue link has been updated, so that now when dumping a character you get: http://crawl.ufetubus.com/morgue/Tasonir/Tasonir.txt, but that directory still doesn't exist on the server and you'll get a 404 error when attempting to access the file.  

I'm not a server admin, but I'm assuming you need to have permissions set up on that directory so it can actually write the file, and for public access to it.  Possibly ask other crawl server admins/dev team members what's required if it's unclear.

**Comment by Sandman25DCSS** [comment]
The link was fixed to use ufetubus  but still there is no file at location http://crawl.ufetubus.com/morgue/Sandman25/Sandman25.txt

**Comment by jeremygurr** [comment]
Oops. I had fixed it, but then broke it again on the next deployment because the change didn't fully get to where it needed to be. Working now.
