### ISSUE TITLE
All arrows are reported as unlinked items and travel is interrupted

### ISSUE THREAD

**Issue by Sandman25DCSS** [jeremygurr/crawl_spicy#4]
![image](https://user-images.githubusercontent.com/12790660/36931522-213e6fb8-1ec0-11e8-8d0f-4d41532248fa.png)

http://crawl.ufetubus.com:8081/#play-dcss_spicy-0.22-a1

**Comment by Sandman25DCSS** [comment]
The game is barely playable because of this bug as I need to manually use stairs and press escape/enter several times for each floor. I got 2 runes but after spending about 5 minutes to return to dungeon I decided to suspend my game as it will be another 5 minutes of pain to finally enter Vaults.

**Comment by tasonir** [comment]
I had this bug happen to me with bolts, but fortunately for me it only happened a few times, so to get out from lair:6 I only had to use fast travel about 3 times.  It didn't happen to me much past lair.  Wasn't too bad, but it's certainly a reproducible issue.

**Comment by jeremygurr** [comment]
Ok I think I have this fixed for now. Reopen the issue if it's still not working.
