### ISSUE TITLE
Crash on starting game - skill_cost_level of 1 out of range 1 (1)

### ISSUE THREAD

**Issue by alexjurkiewicz** [jeremygurr/crawl_spicy#9]
`skill_cost_level of 1 out of range 1 (1) .. Options.max_skill_level + 1 (1)`

https://crawl.project357.org/morgue/chequers/crash-chequers-20180306-105413.txt

**Comment by alexjurkiewicz** [comment]
Seems to only happen when `all_spicy_features=true` is set.

It doesn't happen when I set:
```
no_exp_cap=true
multiple_difficulty_levels=true
different_experience_sources=true
heal_wounds_potion_gives_full_health=true
magic_potion_gives_full_magic=true
monsters_do_not_use_stairs=true
instakill_protection=true
inventory_expansion=true
shield_convenience=true
wide_spell_list=true
extra_numbers=true
no_spellpower_cap=true
unlimited_ammo=true
```

**Comment by jeremygurr** [comment]
I'm having trouble reproducing this. I set only all_spicy_features to true, ran it in console and webtiles mode, tried a few different characters, ran from previously existing characters, and nothing crashed it. Make sure you are using the latest version, and if it's still crashing, give me more details about how to reproduce the problem.

**Comment by alexjurkiewicz** [comment]
Hm, I think it was only happening when I ran crawl with `-extra-option-first all_spicy_features=true`. Let me try and replicate again tonight.

**Comment by alexjurkiewicz** [comment]
can't replicate this with latest build either
